---
- name: Install Java 1.7
  yum: name=java-{{java_version}}-openjdk state=present

- name: add group database
  group: name={{database_password}}
  
- name: use variable from vault
  group: name={{db_password}}
  
